Vanilla OpenLDAP 2.7.0

diff --git a/contrib/slapd-modules/variant/tests/scripts/test001-config b/contrib/slapd-modules/variant/tests/scripts/test001-config
--- a/contrib/slapd-modules/variant/tests/scripts/test001-config
+++ b/contrib/slapd-modules/variant/tests/scripts/test001-config
@@ -59,7 +59,7 @@ if test $RC != 0 ; then
 fi
 
 echo "Stopping slapd on TCP/IP port $PORT1..."
-kill -HUP $KILLPIDS
+kill -HUP $KILLPIDS && wait $KILLPIDS || exit $?
 KILLPIDS=""
 sleep $SLEEP0
 echo "Starting slapd on TCP/IP port $PORT1..."
@@ -96,6 +96,12 @@ echo "database config" >>$CONF2
 echo "rootpw `$SLAPPASSWD -T $CONFIGPWF`" >>$CONF2
 
 $SLAPADD -f $CONF2 -l $LDIFORDERED
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -Tt -f $CONF2 -F $TESTDIR/conftest -d $LVL >> $LOG2 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -186,7 +192,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo "Filtering ldapsearch results..."
 $LDIFFILTER -s e < $SERVER1OUT > $SERVER1FLT
@@ -204,6 +210,6 @@ fi
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/data/regressions/its7573/its7573 b/tests/data/regressions/its7573/its7573
--- a/tests/data/regressions/its7573/its7573
+++ b/tests/data/regressions/its7573/its7573
@@ -33,6 +33,12 @@ $SLAPPASSWD -g -n >$CONFIGPWF
 echo "Starting slapd on TCP/IP port $PORT1... $PWD"
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CONFDIR -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 cd $TESTDIR
 $SLAPD -F ./slapd.d -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
@@ -112,10 +118,10 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/data/regressions/its8444/its8444 b/tests/data/regressions/its8444/its8444
--- a/tests/data/regressions/its8444/its8444
+++ b/tests/data/regressions/its8444/its8444
@@ -61,6 +61,12 @@ while [ $n -le $MPR ]; do
 	mkdir -p ${XDIR}$n $DBDIR.1 $DBDIR.2 $CFDIR
 	. $CONFFILTER $BACKEND < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
@@ -313,10 +319,10 @@ EOF
 	modloop=`expr $modloop + 1`
 done
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/data/regressions/its8800/its8800 b/tests/data/regressions/its8800/its8800
--- a/tests/data/regressions/its8800/its8800
+++ b/tests/data/regressions/its8800/its8800
@@ -58,7 +58,19 @@ while [ $n -le $MPR ]; do
 	mkdir -p ${XDIR}$n $DBDIR.1 $DBDIR.2 $CFDIR
 	. $CONFFILTER $BACKEND < $ITSDIR/slapd-provider${n}.ldif > $CONFLDIF
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	$SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
@@ -130,7 +142,7 @@ echo "done"
 
 echo -n "Stopping MPR1 slapd..."
 kill -HUP $MPID
-wait $MPID
+wait $MPID || { kill -HUP $KILLPIDS; exit 1; }
 KILLPIDS=`echo "$KILLPIDS " | sed -e "s/ $MPID / /"`;
 sleep $SLEEP2
 echo "done"
@@ -142,6 +154,12 @@ mv $DBDIR.1 $DBDIR.1.orig
 mv $DBDIR.2 $DBDIR.2.orig
 mkdir -p $DBDIR.1 $DBDIR.2
 $SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 echo "done"
 
 echo "Starting provider1 slapd on TCP/IP URI $URI1"
@@ -184,6 +202,12 @@ n=1
 while [ $n -le 4 ]; do
 	CFDIR=${XDIR}$n/slapd.d
 	$SLAPCAT -F $CFDIR -b $BASEDN -l $TESTDIR/finaldb-$n.ldif
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapcat failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
@@ -199,10 +223,10 @@ while [ $n -le 4 ]; do
 	n=`expr $n + 1`
 done
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/data/regressions/its9051/its9051 b/tests/data/regressions/its9051/its9051
--- a/tests/data/regressions/its9051/its9051
+++ b/tests/data/regressions/its9051/its9051
@@ -38,7 +38,18 @@ echo "Initializing server configuration for provider..."
 mkdir -p ${XDIR} $DBDIR.1 $DBDIR.2 $CFDIR
 . $CONFFILTER $BACKEND < $ITSDIR/slapd-provider.ldif > $CONFLDIF
 $SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPADD -F $CFDIR -q -b $BASEDN -l $ITSDIR/db.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 KILLPIDS=
 CFDIR=${XDIR}/slapd.d
@@ -163,7 +174,7 @@ echo "Exporting accesslog database..."
 $SLAPCAT -F $CFDIR -b cn=accesslog -l $TESTDIR/accesslogdb.ldif
 RC=$?
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 # 1 root entry, 2 binds, 3 searches, 1 compare
 count=7
@@ -180,6 +191,6 @@ else
     fi
 fi
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit $RC
diff --git a/tests/data/regressions/its9282/its9282 b/tests/data/regressions/its9282/its9282
--- a/tests/data/regressions/its9282/its9282
+++ b/tests/data/regressions/its9282/its9282
@@ -56,6 +56,12 @@ while [ $n -le $MMR ]; do
 	fi
 	sed -e "s/@SID@/$n/g" -e "s|@URI@|$MYURI|g" $TESTDIR/config${n}.ldif > $CONFLDIF
 	$SLAPADD -F $CFDIR -n 0 -l $CONFLDIF
+	RC=$?
+	if test $RC != 0 ; then
+		echo "slapadd failed ($RC)!"
+		exit $RC
+	fi
+
 	n=`expr $n + 1`
 done
 
@@ -160,7 +166,7 @@ fi
 
 echo -n "Stopping MMR1 slapd..."
 kill -HUP $MPID
-wait $MPID
+wait $MPID || { kill -HUP $KILLPIDS; exit 1; }
 KILLPIDS=`echo "$KILLPIDS " | sed -e "s/ $MPID / /"`;
 sleep $SLEEP2
 echo "done"
@@ -258,10 +264,10 @@ if test $RC != 0 ; then
     exit $RC
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/scripts/test006-acls b/tests/scripts/test006-acls
--- a/tests/scripts/test006-acls
+++ b/tests/scripts/test006-acls
@@ -63,6 +63,120 @@ fi
 
 cat /dev/null > $SEARCHOUT
 
+echo "Testing restrictop handling..."
+
+echo "# A search by rootdn gets waved through"
+$LDAPSEARCH -H $URI1 -D "$MANAGERDN" -w $PASSWD \
+	-b "$BABSDN" -s base \
+	-e "assert=(entryDN=)" "(objectclass=*)" \
+	>>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+122)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# A search with a control that gets dropped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -M \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control that can't be dropped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -MM \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+53)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# Same search by a user that's allowed to use it"
+$LDAPSEARCH -H $URI1 -D "$BJORNSDN" -w bjorn -b "$BABSDN" -s base -MM \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control combination that is stripped"
+$LDAPSEARCH -H $URI1 -b "$BABSDN" -s base -M -e "assert=(entryDN=)" \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "# A search with a control combination that is rejected"
+$LDAPSEARCH -H $URI1 -D "$BABSDN" -w bjensen \
+	-b "$BABSDN" -s base -M -e "assert=(entryDN=)" \
+	"(objectclass=*)" >>$SEARCHOUT 2>&1
+RC=$?
+case $RC in
+53)
+	;;
+0)
+	echo "ldapsearch should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+echo "# A password modify is not allowed"
+$LDAPPASSWD -H $URI1 -D "$BABSDN" -w bjensen -a bjensen -s changed \
+	>> $SEARCHOUT 2>&1
+RC=$?
+case $RC in
+1|53)
+	# ldappasswd currently returns 1 on any error
+	;;
+0)
+	echo "ldappasswd should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldappasswd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+cat /dev/null > $SEARCHOUT
+
 echo "# Try to read an entry inside the Alumni Association container.
 # It should give us noSuchObject if we're not bound..." \
 >> $SEARCHOUT
@@ -613,6 +727,27 @@ case $RC in
 	;;
 esac
 
+$LDAPMODIFY -D "$BABSDN" -H $URI1 -w bjensen -M >> \
+	$TESTOUT 2>&1 << EOMODS15a
+dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
+changetype: delete
+EOMODS15a
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
 $LDAPMODIFY -D "$BABSDN" -H $URI1 -w bjensen >> \
 	$TESTOUT 2>&1 << EOMODS15
 dn: cn=Added by Bjorn (will be deleted),ou=Add & Delete,dc=example,dc=com
@@ -635,12 +770,141 @@ case $RC in
 	;;
 esac
 
+$LDAPMODIFY -D "$JAJDN" -H $URI1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS16
+dn: ou=People,dc=example,dc=com
+changetype: modify
+increment: uidNumber
+uidNumber: 50
+-
+EOMODS16
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$JAJDN" -H $URI1 -w jaj >> \
+	$TESTOUT 2>&1 << EOMODS17
+dn: ou=People,dc=example,dc=com
+changetype: modify
+replace: gidNumber
+gidNumber: 50
+-
+EOMODS17
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$BJORNSDN" -H $URI1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS18
+dn: ou=People,dc=example,dc=com
+changetype: modify
+increment: uidNumber
+uidNumber: 55
+-
+EOMODS18
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$BABSDN" -H $URI1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS19
+dn: ou=People,dc=example,dc=com
+changetype: modify
+increment: uidNumber
+uidNumber: -1
+-
+EOMODS19
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$BABSDN" -H $URI1 -w bjensen >> \
+	$TESTOUT 2>&1 << EOMODS20
+dn: ou=People,dc=example,dc=com
+changetype: modify
+increment: uidNumber
+uidNumber: 1
+-
+EOMODS20
+RC=$?
+case $RC in
+0)
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
+$LDAPMODIFY -D "$BJORNSDN" -H $URI1 -w bjorn >> \
+	$TESTOUT 2>&1 << EOMODS21
+dn: ou=People,dc=example,dc=com
+changetype: modify
+replace: uidNumber
+uidNumber: 55
+-
+EOMODS21
+RC=$?
+case $RC in
+50)
+	;;
+0)
+	echo "ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+	;;
+*)
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
 echo "Using ldapsearch to retrieve all the entries..."
 echo "# Using ldapsearch to retrieve all the entries..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$BASEDN" -H $URI1 \
 	    'objectClass=*' >> $SEARCHOUT 2>&1
 RC=$?
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	exit $RC
@@ -662,6 +926,6 @@ fi
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/scripts/test022-ppolicy b/tests/scripts/test022-ppolicy
--- a/tests/scripts/test022-ppolicy
+++ b/tests/scripts/test022-ppolicy
@@ -87,6 +87,18 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+echo "Testing group based matching..."
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	"uid=another, ou=People, dc=example, dc=com" \
+	"pwdPolicySubentry:cn=Another Policy, ou=Policies, dc=example, dc=com" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 6 ; then
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
 echo "Testing account lockout..."
 $LDAPSEARCH -H $URI1 -D "$USER" -w wrongpw >$SEARCHOUT 2>&1
 sleep 2
@@ -107,9 +119,14 @@ DELAYATTR=`$LDAPSEARCH -D "$MANAGERDN" -H $URI1 -w $PASSWD -b "$USER" -E account
 echo "$DELAYATTR" >> $SEARCHOUT
 DELAY=`echo "$DELAYATTR" | sed -n -e 's/.*seconds_before_unlock=\([[:digit:]]*\)/\1/p'`
 
-echo "Waiting $DELAY seconds for lockout to reset..."
-sleep $DELAY
-sleep 1
+# $DELAY is empty if we were so slow that the lockout expired already,
+# continue test but the next part might fail anyway since we rely on
+# cumulative timing
+if test -n "$DELAY" ; then
+	echo "Waiting $DELAY seconds for lockout to reset..."
+	sleep $DELAY
+	sleep 1
+fi
 
 $LDAPSEARCH -e ppolicy -H $URI1 -D "$USER" -w $PASS \
 	-b "$BASEDN" -s base >> $SEARCHOUT 2>&1
@@ -125,9 +142,12 @@ echo "$DELAYATTR" >> $SEARCHOUT
 DELAY=`echo "$DELAYATTR" | sed -n -e 's/.*expire=\([[:digit:]]*\)/\1/p'`
 
 echo "Testing password expiration"
-echo "Waiting $DELAY seconds for password to expire..."
-sleep $DELAY
-sleep 1
+# $DELAY is empty if we were so slow that the password expired already
+if test -n "$DELAY" ; then
+	echo "Waiting $DELAY seconds for password to expire..."
+	sleep $DELAY
+	sleep 1
+fi
 
 $LDAPSEARCH -e ppolicy -H $URI1 -D "$USER" -w $PASS \
 	-b "$BASEDN" -s base > $SEARCHOUT 2>&1
@@ -245,6 +265,16 @@ fi
 echo "Testing failed logins when password/policy missing..."
 
 $LDAPSEARCH -e ppolicy -H $URI1 \
+	-D "$PWADMIN" -w hasnopolicy \
+	-b "$BASEDN" -s base > $SEARCHOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "Password accepted ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+$LDAPSEARCH -e ppolicy -H $URI1 \
 	-D "uid=test, ou=People,$BASEDN" -w hasnopolicy \
 	-b "$BASEDN" -s base > $SEARCHOUT 2>&1
 RC=$?
@@ -304,6 +334,22 @@ if test $COUNT != 1 ; then
 	exit 1
 fi
 
+# The add is rejected because ppolicy restricts the connection to password change.
+echo "Testing ppolicy control reject on add while connection restricted..."
+$LDAPADD -e ppolicy -H $URI1 -D "$USER" -w $PASS >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=dummy,ou=People,dc=example,dc=com
+objectClass: person
+cn: dummy
+sn: dummy
+EOMODS
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapadd should have been rejected!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
 echo "Clearing forced reset..."
 
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
@@ -337,6 +383,22 @@ $LDAPPASSWD -H $URI1 \
 RC=$?
 if test $RC = 0 ; then
 	echo "Safe modify test 1 failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+# The modify is rejected because pwdSafeModify requires the old password.
+echo "Testing ppolicy control reject on modify without old password..."
+$LDAPMODIFY -e ppolicy -H $URI1 -D "$USER" -w $PASS >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: $USER
+changetype: modify
+replace: userPassword
+userPassword: newpassword1
+EOMODS
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapmodify should have been rejected!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
@@ -469,16 +531,34 @@ if test $RC = 0 ; then
 	exit 1
 fi
 
+# The add is rejected because the password is shorter than pwdMinLength.
+echo "Testing ppolicy control reject on add with short password..."
+$LDAPADD -e ppolicy -H $URI1 -D "$USER" -w $PASS >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: uid=weakpw,ou=People,dc=example,dc=com
+objectClass: top
+objectClass: person
+objectClass: inetOrgPerson
+cn: Weak Password
+uid: weakpw
+sn: Weak
+userPassword: ab
+EOMODS
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapadd should have been rejected!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
 echo "Testing idle password expiration"
-echo "Reconfiguring policy to replace expiration with idle expiration..."
+echo "Switching to a policy with idle expiration..."
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=Standard Policy, ou=Policies, dc=example, dc=com
+dn: $USER
 changetype: modify
-delete: pwdMaxAge
--
-add: pwdMaxIdle
-pwdMaxIdle: 15
+add: description
+description: idle
 
 EOMODS
 RC=$?
@@ -486,6 +566,16 @@ if test $RC != 0 ; then
 	echo "ldapmodify failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
+fi
+
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	"$USER" "pwdPolicySubentry:cn=Idle Expiration Policy, ou=Policies, dc=example, dc=com" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 6 ; then
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
 $LDAPSEARCH -e ppolicy -H $URI1 -D "$USER" -w $PASS \
@@ -508,15 +598,27 @@ if test $RC != 49 ; then
 	exit 1
 fi
 
-echo "Reverting policy changes..."
+echo "Listing a password hashed with a custom default, then rehashing..."
+
+# {SHA} is good that it doesn't use salt, we don't expect the base64 binary on
+# all systems we support, so we precomputed the expected value:
+# passwd -h '{SHA}' -s hashed -n | base64
+$LDAPSEARCH -o ldif-wrap=no -H $URI1 -D "$MANAGERDN" -w $PASSWD \
+    -b "uid=hashed, ou=People, dc=example, dc=com" userPassword | \
+    grep -q "userPassword:: e1NIQX1ZeGhWT0puYXJpbEJjWXdDVUlydTZUaXZHaHc9"
+RC=$?
+if test $RC != 0 ; then
+	echo "Unexpected password hash returned!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=Standard Policy, ou=Policies, dc=example, dc=com
+dn: cn=Hashing Policy, ou=Policies, dc=example, dc=com
 changetype: modify
-delete: pwdMaxIdle
--
-add: pwdMaxAge
-pwdMaxAge: 30
+replace: pwdDefaultHash
+pwdDefaultHash: {SSHA}
 
 EOMODS
 RC=$?
@@ -524,6 +626,59 @@ if test $RC != 0 ; then
 	echo "ldapmodify failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
+fi
+
+# '{SSHA}' fits nicely onto base64 chunk length, we don't have to work too hard
+# to check it as a prefix
+$LDAPSEARCH -H $URI1 -D "uid=hashed, ou=People, dc=example, dc=com" -w hashed \
+    -b "uid=hashed, ou=People, dc=example, dc=com" | \
+    grep -q '^userPassword:: e1NTSEF9'
+RC=$?
+if test $RC != 0 ; then
+	echo "Password not rehashed as configured!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	"uid=hashed, ou=People, dc=example, dc=com" "pwdReset:FALSE" \
+	>> $TESTOUT 2>&1
+RC=$?
+case $RC in
+6)
+	;;
+16)
+	;;
+*)
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+esac
+
+echo "Reverting to Standard policy..."
+$LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: $USER
+changetype: modify
+delete: description
+description: idle
+
+EOMODS
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	"$USER" "pwdPolicySubentry:cn=Standard Policy, ou=Policies, dc=example, dc=com" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 6 ; then
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
 if test "$BACKLDAP" != "ldapno" && test "$SYNCPROV" != "syncprovno"  ; then 
@@ -534,12 +689,12 @@ mkdir $DBDIR2
 sed -e "s,$DBDIR1,$DBDIR2," < $CONF1 > $CONF2
 echo "Starting slapd consumer on TCP/IP port $PORT2..."
 $SLAPD -f $CONF2 -h $URI2 -d $LVL > $LOG2 2>&1 &
-PID=$!
+CONSUMERPID=$!
 if test $WAIT != 0 ; then
-    echo PID $PID
+    echo CONSUMERPID $CONSUMERPID
     read foo
 fi
-KILLPIDS="$KILLPIDS $PID"
+KILLPIDS="$KILLPIDS $CONSUMERPID"
 
 echo "Configuring syncprov on provider..."
 if [ "$SYNCPROV" = syncprovmod ]; then
@@ -698,15 +853,15 @@ if test $RC != 0 ; then
 fi
 
 echo "Reconfiguring policy to remove grace logins..."
-$LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
+$LDAPMODIFY -v -D cn=config -H $URI1 -y $CONFIGPWF >> \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=Standard Policy, ou=Policies, dc=example, dc=com
-changetype: modify
-delete: pwdGraceAuthnLimit
--
-replace: pwdMaxAge
-pwdMaxAge: 15
--
+dn: cn={0}Stricter Policy,olcOverlay={0}ppolicy,olcDatabase={1}$BACKEND,cn=config
+changetype: add
+objectClass: olcPPolicyScopedRule
+olcPPolicyRuleObject: dc=example,dc=com
+olcPPolicyRuleScope: sub
+olcPPolicyRuleGroup: cn=Policy Group, ou=Groups, dc=example, dc=com
+olcPPolicyRulePolicy: cn=Stricter Policy, ou=Policies, dc=example, dc=com
 
 EOMODS
 RC=$?
@@ -714,6 +869,47 @@ if test $RC != 0 ; then
 	echo "ldapmodify failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
+fi
+
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	"$USER" "pwdPolicySubentry:cn=Stricter Policy, ou=Policies, dc=example, dc=com" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 6 ; then
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
+
+# URI2 is not running unless we performed chaining test above
+if test -n "$CONSUMERPID"; then
+$LDAPMODIFY -v -D cn=config -H $URI2 -y $CONFIGPWF >> \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn={0}Stricter Policy,olcOverlay={0}ppolicy,olcDatabase={1}$BACKEND,cn=config
+changetype: add
+objectClass: olcPPolicyScopedRule
+olcPPolicyRuleObject: dc=example,dc=com
+olcPPolicyRuleScope: sub
+olcPPolicyRuleGroup: cn=Policy Group, ou=Groups, dc=example, dc=com
+olcPPolicyRulePolicy: cn=Stricter Policy, ou=Policies, dc=example, dc=com
+
+EOMODS
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+$LDAPCOMPARE -D "$MANAGERDN" -H $URI2 -w $PASSWD \
+	"$USER" "pwdPolicySubentry:cn=Stricter Policy, ou=Policies, dc=example, dc=com" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 6 ; then
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
+fi
 fi
 
 OLDPASS=$PASS
@@ -743,8 +939,12 @@ DELAY=`echo "$DELAYATTR" | sed -n -e 's/.*expire=\([[:digit:]]*\)/\1/p'`
 DELAY=`expr $DELAY - 10`
 
 echo "Testing password expiration"
-echo "Waiting $DELAY seconds for password to expire..."
-sleep $DELAY
+# $DELAY is empty if we were so slow that the password expired already
+if test -n "$DELAY" ; then
+	echo "Waiting $DELAY seconds for password to expire..."
+	sleep $DELAY
+	sleep 1
+fi
 
 $LDAPSEARCH -H $URI1 -D "$USER" -w $PASS \
 	-b "$BASEDN" -s base > $SEARCHOUT 2>&1
@@ -773,10 +973,10 @@ if test $COUNT = 0 ; then
 	exit 1
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
diff --git a/tests/scripts/test045-syncreplication-proxied b/tests/scripts/test045-syncreplication-proxied
--- a/tests/scripts/test045-syncreplication-proxied
+++ b/tests/scripts/test045-syncreplication-proxied
@@ -237,7 +237,7 @@ fi
 CHECK=`expr $CHECK + 1`
 echo "$CHECK > Stopping the provider, sleeping $SLEEP2 seconds and restarting it..."
 kill -HUP "$PROVIDERPID"
-wait $PROVIDERPID
+wait $PROVIDERPID || { kill -HUP $KILLPIDS; exit 1; }
 sleep $SLEEP2
 
 echo "======================= RESTART =======================" >> $LOG1
@@ -411,9 +411,9 @@ if test $RC != 0 ; then
 fi
 
 #echo "Filtering provider results..."
-$LDIFFILTER < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
+$LDIFFILTER -s a < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
 #echo "Filtering consumer results..."
-$LDIFFILTER < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
+$LDIFFILTER -s a < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
 
 echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
@@ -427,7 +427,7 @@ fi
 CHECK=`expr $CHECK + 1`
 echo "$CHECK > Stopping proxy to test recovery..."
 kill -HUP $PROXYPID
-wait $PROXYPID
+wait $PROXYPID || { kill -HUP $KILLPIDS; exit 1; }
 
 echo "Modifying more entries on the provider..."
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
@@ -518,9 +518,9 @@ if test $RC != 0 ; then
 fi
 
 #echo "Filtering provider results..."
-$LDIFFILTER < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
+$LDIFFILTER -s a < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
 #echo "Filtering consumer results..."
-$LDIFFILTER < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
+$LDIFFILTER -s a < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
 
 echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
@@ -607,9 +607,9 @@ if test $RC != 0 ; then
 fi
 
 #echo "Filtering provider results..."
-$LDIFFILTER < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
+$LDIFFILTER -s a < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
 #echo "Filtering consumer results..."
-$LDIFFILTER < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
+$LDIFFILTER -s a < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
 
 echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
@@ -623,7 +623,7 @@ fi
 CHECK=`expr $CHECK + 1`
 echo "$CHECK > Stopping consumer to test recovery..."
 kill -HUP $CONSUMERPID
-wait $CONSUMERPID
+wait $CONSUMERPID || { kill -HUP $KILLPIDS; exit 1; }
 
 echo "Modifying more entries on the provider..."
 $LDAPMODIFY -v -D "$MANAGERDN" -H $URI1 -w $PASSWD >> \
@@ -704,61 +704,17 @@ if test $RC != 0 ; then
 fi
 
 #echo "Filtering provider results..."
-$LDIFFILTER < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
+$LDIFFILTER -s a < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
 #echo "Filtering consumer results..."
-$LDIFFILTER < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
+$LDIFFILTER -s a < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
 
 echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
 
 if test $? != 0 ; then
-	# FIXME: keep the original workaround in place, in case we needed again
-	if test 1 = 1 ; then
-		echo "test failed - provider and consumer databases differ"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit 1
-	fi
-
-	echo "	test failed - provider and consumer databases differ (ignored by now)"
-	echo "	Stopping proxy to see if it auto-recovers..."
-	kill -HUP $PROXYPID
-	wait $PROXYPID
-
-	echo "	${CHECK}.1 > Restarting proxy..."
-	echo "======================= RESTART =======================" >> $LOG3
-	$SLAPD -f $CONF3 -h $URI3 -d $LVL >> $LOG3 2>&1 &
-	PROXYPID=$!
-	if test $WAIT != 0 ; then
-		echo PROXYPID $PROXYPID
-		read foo
-	fi
-	KILLPIDS="$PROVIDERPID $CONSUMERPID $PROXYPID"
-
-	echo "	Waiting $SLEEP2 seconds for syncrepl to receive changes..."
-	sleep $SLEEP2
-
-	#echo "Using ldapsearch to read all the entries from the consumer..."
-	$LDAPSEARCH -S "" -b "$BASEDN" -H $URI2 \
-		'(objectClass=*)' > "${CONSUMEROUT}.5.1" 2>&1
-	RC=$?
-
-	if test $RC != 0 ; then
-		echo "	ldapsearch failed at consumer ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-	fi
-
-	#echo "Filtering consumer results..."
-	$LDIFFILTER < "${CONSUMEROUT}.5.1" > $CONSUMERFLT
-
-	echo "	${CHECK}.1 < Comparing retrieved entries from provider and consumer..."
-	$CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
-
-	if test $? != 0 ; then
-		echo "	test failed - provider and consumer databases differ"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit 1
-	fi
+	echo "test failed - provider and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
 #
@@ -844,24 +800,23 @@ if test $RC != 0 ; then
 fi
 
 #echo "Filtering provider results..."
-$LDIFFILTER < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
+$LDIFFILTER -s a < "${PROVIDEROUT}.$CHECK" > $PROVIDERFLT
 #echo "Filtering consumer results..."
-$LDIFFILTER < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
+$LDIFFILTER -s a < "${CONSUMEROUT}.$CHECK" > $CONSUMERFLT
 
 echo "$CHECK < Comparing retrieved entries from provider and consumer..."
 $CMP $PROVIDERFLT $CONSUMERFLT > $CMPOUT
 
 if test $? != 0 ; then
-	echo "test failed - provider and consumer databases differ (ignored by now)"
-	#echo "test failed - provider and consumer databases differ"
-	#test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	#exit 1
+	echo "test failed - provider and consumer databases differ"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit 1
 fi
 
-test $KILLSERVERS != no && kill -HUP $KILLPIDS
+test $KILLSERVERS != no && { kill -HUP $KILLPIDS || exit $?; }
 
 echo ">>>>> Test succeeded"
 
-test $KILLSERVERS != no && wait
+test $KILLSERVERS != no && { wait $KILLPIDS || exit $?; }
 
 exit 0
